language: cpp
compiler: gcc
dist: trusty

before_install:
  # C++14
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  
install:
  # C++14
  - sudo apt-get install -qq g++-6
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90
  
script:
  - mkdir build
  - cd build
  - cmake ..
  - make   
  - ./Testing-Tasks

after_success:
  - cd ${TRAVIS_BUILD_DIR}
  - lcov --directory . --capture --output-file coverage.info
  - lcov --remove coverage.info '/user/*' --output-file coverage.info
  - lcov --list coverage.info
  - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"
